### ISSUE TITLE
What If accessToken expires?

### ISSUE THREAD

**Issue by hasgar** [twilio/voice-quickstart-swift#100]
In my twilio callkit integrated app,when user open the app Initialising twilio session with an accessToken with default expiration time(24 hours)..user never open the app for next two days..and after two days user get a call, will call kit notify the user or not?

sorry for noob question

**Comment by bchen-twilio** [comment]
Hi @hasgar 

No problem! This is totally a legit question about the Access Token and the incoming capability and we are sorry for the confusion.

The Twilio Access Token is used for authentication when the application is trying to perform any Twilio operation like making a call or registering for incoming call notifications, and as long as the token has valid expiry value during the request then you are good.

As for when will the ability to receive incoming call push notifications - in the Programmable Voice mobile SDK only when you call `TwilioVoice.unregister()` explicitly (or when the device token of the Apple VoIP Service has been invalidated, which is less likely in the short period of time), the application will be able to get push notifications for incoming call invites, even if the Access Token used for registration has expired.

Once registered, your application will be able to get incoming call notification when the app is active or in the background, or even killed. The VoIP push notification will launch your application and yes there is one thing you should note - you should make sure the implementation of `PkPushRegistry` setup is upfront in the app UI flow in order to make sure your app gets the callback from `PushKit` and can respond to it.

Hope this helps.
-bobie

**Comment by idelgado** [comment]
We recently added a section on access tokens to our README. Hopefully this provides more insight into how access tokens are used. 
https://github.com/twilio/voice-quickstart-swift#access-tokens
