### ISSUE TITLE
Call not receiving after kill the app

### ISSUE THREAD

**Issue by hasgar** [twilio/voice-quickstart-swift#115]
Integrated swift callkit in my app, it was all working fine. After that call is not receiving after killing the app. if app killed, again want to initiated with access Token to get the call. only change i made is removed background fetch from the app configuration. but then I added again still its not working. removed and added certificate again(same old VoIP) and created new push credentials. tried sandbox on and off
Testflight

**Comment by bchen-twilio** [comment]
Hi @hasgar 

Thanks for reaching out to the team.
Assuming the call push notifications are delivered successfully, the application will be woken up by the system and guaranteed with enough time to present the call to the user. One thing you will have to make sure is that the implementation of `PkPushRegistry` has to be in `AppDelegate` (or the frontmost app-delegate object in your app) or the entry view-controller. We've seen applications that keep `PkPushRegistry` object behind a sign-in view and the session has expired so that it could fail to initialize the `PkPushRegistry` and respond to the `PushKit` callbacks.

**Comment by hasgar** [comment]
@bchen-twilio thank you.. it works.. but when initializing on UI is hanging for few seconds..

**Comment by bchen-twilio** [comment]
Cool! I'll suggest maybe you can move the initialization to app-delegate then the impact will be less noticeable.
I'll close this issue for now but feel free to open a new ticket.

-bobie
