### ISSUE TITLE
The push notification was rejected by APNs

### ISSUE THREAD

**Issue by alexanderkhitev** [twilio/voice-quickstart-swift#123]
Hello! I'm trying to make the first call to my application using a local server, but I get this error. "The push notification was rejected by APNs", please tell me how it can be fixed?

**Comment by bchen-twilio** [comment]
Hi @alexanderkhitev 

Not sure if the issue has been resolved on your end since you closed the ticket.
One possible root cause could be that you are using a regular APNS certificate, instead of a VoIP Service certificate. To enable incoming call notifications using the Voice SDK, you will need to use a VoIP Service certificate. The README should give you the directions.

Please also note that you need to use a fresh CSR (certificate signing request) file, which has not been used for requesting APNS certificate. We've seen people getting notification delivery failure with such case.

-bobie

**Comment by alexanderkhitev** [comment]
Hi @bchen-twilio 

Yes, thank you, it was the creation of a new CSR that helped solve the problem.

**Comment by bchen-twilio** [comment]
Cool 👍
