### ISSUE TITLE
didReceiveIncomingPushWithPayload called twice

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#131]
Hello Twilio Support,

I'm currently using TwilioVoice 2.0.0-beta14 in my iOS application for VoIP calling. Recently I have noticed that when I'm making an incoming call the `didReceiveIncomingPushWithPayload` delegate method is getting called twice. First time it is called when there is an incoming call, second time it is called when the incoming call is received or cancelled.

Why is it working like this?

Thanks

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

Twilio Voice service is designed the way that it allows same identity to be used on multiple devices (but under the same Twilio Account SID). All of the clients with the same identity will receive the call notification. When the call is accepted or rejected by one of the clients, everyone will receive a canceled notification, including the mobile client who answered the call.

By the way, have you tried the latest version (2.0.4) of the Voice iOS SDK? there is not much difference in terms of APIs but we've been working hard to include a lot of improvements in the latest versions.

-bobie

**Comment by ojhakapil** [comment]
Hi @bchen-twilio 

Thanks for your reply.

Is there a way to differentiate between a Call Notification and a Cancel Notification? 

I will try version 2.0.4 soon.

**Comment by ojhakapil** [comment]
I'm trying to implement CallKit in my existing app , when an incoming call is received and the native incoming call UI is presented then even when I reject the call it again presents the native incoming call UI for iPhone since `didReceiveIncomingPushWithPayload` is called again.

**Comment by bchen-twilio** [comment]
Hi @ojhakapil 

You can actually differentiate the notification by the value of `twi_message_type` in the payload - `twilio.voice.call` and `twilio.voice.cancel`. We don't recommend this approach since the keys and values of the push payload are subject to change by Twilio.
The Voice iOS SDK is also implemented based on the assumption that `call-canceled` notification will also be received, so please make sure that your application passes any VoIP/PushKit notification to the SDK.

As for the CallKit experience, the native call UI should be represented when your application reports the incoming call to the CallKit provider. Report the CallKit call only when the application is getting the `TVONotificationDelegate.callInviteReceived` callback AND `callInvite.state == .pending`. Submit an end-call action to the CallKit provider when you are getting a `.canceled` call-invite. [Follow the quickstart example for more details](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L239).

Thanks
-bobie

**Comment by ojhakapil** [comment]
Thanks.

**Comment by bchen-twilio** [comment]
Closing this ticket for now but please feel free to reach out to us in the future.
