### ISSUE TITLE
Caller: find out when the receiver has answered the call

### ISSUE THREAD

**Issue by demetrio812** [twilio/voice-quickstart-swift#139]
Hello,
while making a call I immediately get the notification TVOCallDelegate.callDidConnect

However this is when the receiver didn't answer yet and the ringtone is playing, I don't get any other update when the receiver answer the call, is there a way to know when this happens?

Thanks,
Dem

**Comment by bchen-twilio** [comment]
Hey @demetrio812 

I totally understand the confusion when you received the delegate callback.
The reason behind is that when you make a call from the Voice SDK, the SDK will try to make a connection to Twilio (we call this the parent leg) then Twilio will decide what to do next based on the instructions in your TwiML response. The most common use case is to `<Dial>` another client or number, which is the child leg of this call scenario.

You probably already knew by now, that the `callDidConnect` callback is fired when the parent leg connection is established.

Currently there is no way for the Voice mobile SDKs to get this callback when the call is actually answered by the remote party, since there might be other use cases. That's why and when we fire the callback.

-bobie

**Comment by iOSMahesh** [comment]
Hi @bchen-twilio ,
is there any other way to detect receiver answered the call at caller side?
This is important to show the timer on the screen. It's useful to indicate call duration to the user.

**Comment by bchen-twilio** [comment]
Hi @iOSMahesh 

You can definitely achieve this by enabling [the answer-on-bridge flag](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) in the <Dial> verb. When a call is made with this flag enabled in the TwiML app, the call will only receive the `callDidConnect:` callback when the callee accepted the call invite.

cheers,
-bobie
