### ISSUE TITLE
Quickstart Example app fails to receive call when backgrounded

### ISSUE THREAD

**Issue by agreensh** [twilio/voice-quickstart-swift#174]
### Description

When the quickstart app is **backgrounded, and the device is not locked,** no incoming calls are reported (after the app has been killed by the OS - so, after 30 secs)

[Note: if the app is in the foreground, incoming calls are reported as expected, if the device is locked, incoming calls are reported some of the time]

### Steps to Reproduce

Run the swift quickstart app.
Background the app.
Call the Twilio number associated with the app.
App does not report an incoming call

#### Code

Debugging the app, this call hangs and no response is returned (error or success)

```
callKitProvider.reportNewIncomingCall(with: uuid, update: callUpdate) { error in
```

The end of the function  ```func reportIncomingCall(from: String, uuid: UUID) {``` is never reached.

#### Expected Behavior

Incoming call notification displayed.

#### Actual Behavior

No notification shown

#### Reproduces How Often

100 % when app backgrounded

#### Voice iOS SDK

2.0.7 via CocoaPods

#### Xcode

10.0

#### iOS Version

12.0

#### iOS Device

iPhone X, iPhone 6 for certain (haven't tried on other iPhones as don't have access)

**Comment by bchen-twilio** [comment]
Hi @agreensh 

One workaround you can try is to initialize the `PkPushRegistry` in a global dispatch queue.

-bobie

**Comment by agreensh** [comment]
Hi bobie,

I tried ```PKPushRegistry.init(queue: DispatchQueue.global())``` to initialise PKPushRegistry. Is that how you meant, on the global queue? I also tried with various qos eg ```DispatchQueue.global(qos: .userInteractive)```

There is no difference. The call is still not received when the app is backgrounded.

**Comment by agreensh** [comment]
Hi bobie,

Is there any update on this.
The company I work for won't commit to using Twilio given that the Twilio supplied demo app doesn't even work - it's not giving them much confidence.

Andy

**Comment by bchen-twilio** [comment]
Hi @agreensh 

We have previously investigated at this issue and found that it seems like a threading issue of PushKit since we do see Twilio call notifcations being received in the iOS system log. We will work on providing a workaround for this issue.

**Comment by bchen-twilio** [comment]
Hey @agreensh 

Quick question: are you using the `pushRegistry:didReceiveIncomingPushWithPayload:forType:` or `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` in your application?
I've done some experiments to initialize `PkPushRegistry` on the main queue or global queue, with the combination of different callback methods. It turned out that when `PkPushRegistry` was init'd on the main queue, the calls were always not shown on the (CallKit) system UI either the `completion` dispatched to the main queue or a global queue. It always worked when the `pushRegistry:didReceiveIncomingPushWithPayload:forType:` method was used, or the method with completion handler but not called.

Bottomline:
- Initialize `PkPushRegistry` on the main queue.
- Use the `pushRegistry:didReceiveIncomingPushWithPayload:forType:` method.
- Or use the `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` on iOS 11+, but don't call the `completion()`.

By the way I was using Xcode 10 and iOS 12 (iPhone8).

Let me know if this helps.
-bobie

**Comment by bchen-twilio** [comment]
Hi Andy

Can you check the iOS system log and see if the incoming call notifications are received even when the phone does not ring? it's a different type of issue if the notification is not properly delivered.
Also please provide more details regarding the callee unable to hang up. We've tried and were able to end the call properly. SDK log would be great.

Thanks,
-bobie

**Comment by piyushtank** [comment]
@agreensh Apologize for the delay. We are working on this issue and soon have an update for you. We figured if the app is in the background and if incoming call is received, as soon as completion handler is invoked, the app goes into background suspended. As a result, the sample app is not able to report the call to the CallKit. @bchen-twilio is working on this - See https://github.com/twilio/voice-quickstart-objc/pull/137 for more information.

**Comment by bchen-twilio** [comment]
Hi @agreensh 

We have updated the sample apps recently and I believe should help resolve the issue your application is experiencing. Please refer to [this pull request](https://github.com/twilio/voice-quickstart-objc/pull/142) and apply necessary updates to your application.

Thanks
-bobie
