### ISSUE TITLE
request time out

### ISSUE THREAD

**Issue by jaenelleisidro** [twilio/voice-quickstart-swift#18]
Hi,

im trying to make twillio phone call work but after receiving token it says request timed out

can you take a look and see why?
[http://stackoverflow.com/questions/42985353/twilio-request-timeout](url)

thanks,
Jay

**Comment by bchen-twilio** [comment]
Hi @jaenelleisidro 

Bobie here from the Voice SDK team.
I am sorry that you are seeing the 408 (timeout) response. This is usually caused due to local network reachability issue and unfortunately there isn't much the SDK can do.
Could you provide us a copy of you access token string? Also does this timeout failure happen all the time or once in a while?

Thanks.

**Comment by jaenelleisidro** [comment]
Hi Bobie,

I already figured out the cause, its about the url of the python backend changed when ngrok started.

now im encountering a different issue. ill gonna file a new issue and close this. 


thanks!
