### ISSUE TITLE
No notifications even when in app

### ISSUE THREAD

**Issue by tommiris** [twilio/voice-quickstart-swift#198]
### Description

If the app view is at the Twilio view controller then a pop up with "accept / reject" etc will come up as expected
If the app view is not at the Twilio view controller (for eg. another view controller or when the app is in the background), nothing happens.
Has VOIP APN set up. Do I also need to add Push Notification APN too (not stated in GitHub readme)? 

If I use CallKit instead, then the call kit is not terminated when the receiver hung up. This results in inability to make or receive calls again as Call Kit isn't terminated. Also CallKit does not reside on the top of my app so there is no way to at least terminate the call manually. 

### Steps to Reproduce

Client to client calls

#### Code

Standard code supplied on GitHub (VoiceCall - no Callkit)

#### Expected Behavior

Expect notification of incoming calls at least in-app

#### Actual Behavior

No notifications

#### Reproduces How Often

Every time

#### Logs

```
// Log output when the issue occurs
```

### Versions

Swift 4.0
iOS 12.1

#### Voice iOS SDK

Latest

#### Xcode

10.1

#### iOS Version

12.1

#### iOS Device

iPad mini 4

**Comment by bchen-twilio** [comment]
Hi @tommiris 

For the app being able to respond to the VoIP notifications, the component that instantiates and owns the `PkPushRegistry` must be alive when the app receives the notification.

-bobie

**Comment by bchen-twilio** [comment]
Hi @tommiris 

I am closing this issue and assuming [this pull request](https://github.com/twilio/voice-quickstart-swift/pull/195) has addressed the issue - we fixed the flow to fulfill the incoming push handler completion so that the app won't get stuck in the background-suspended state before it can report the incoming call and show to the users.

Please feel free to let me know if you need help applying the fix to your application.

Thanks,
-bobie
