### ISSUE TITLE
Client to client outgoing call fails to connect randomly but CallKit UI starts

### ISSUE THREAD

**Issue by aksthelion** [twilio/voice-quickstart-swift#212]
Re-opening the issue #197 

Please don't assume that call is connected when callkit UI shows. This is not the case. In my case callKit UI shows but call is NOT started/connected.

1) Callkit UI is started
2) Call is not started/connected. There is no call in progress, there is no uuid, there is nothing related with a call.

### Description
Client to client outgoing call fails first time after install. When tapped on call button callKit is fired in the background but nothing happens.

This always happens first time after installation of my app. When this happens callKit UI runs in the background as I can see it by sending app to the background. I've to kill the app and start again. After few attempts it works. 

Once it starts working I no longer see this problem in the device any more until app is reinstalled and then it repeats.

It's random.

### Steps to Reproduce

1. Run it on iPhone 7S and initiate client to client call

#### Expected Behavior

It should either connect or return failure and kill callKit.

#### Actual Behavior

Neither connects nor kills callKit. callKit UI keeps running in the background.

#### Reproduces How Often

Over 90% of time.

#### Logs

```
StartCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 7.)
```
error 7 is CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached

#### Voice iOS SDK

2.0.7 via CocoaPods

#### iOS Version

12.1.1

#### iOS Device

iPhone 5s, iPhone 7 Plus

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

I tried using the quickstart to make about a dozen of (first) calls but was not able to reproduce the failure. By the way 2.0.0-beta13 seems to be pretty outdated and it would be great if you can update to the latest version since throughout the releases we have also added couple of audio fixes to the SDK.

Thanks
-bobie

**Comment by aksthelion** [comment]
I'm using latest 2.0.7 version, I hope this is latest one?

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

My mistake, 2.0.7 is the latest version. I guess it's because of the issue template is still on the old version.
I am having hard trying to reproduce the error with the fresh quickstart, but definitely I might have missed something on my side. Not sure if CallKit behaves differently but my test device is on iOS 12.1.3. My steps:
- Fresh quickstart
- Update project settings (bundle ID, dev team)
- Update access token URL in `ViewController.m`
- Build and run
- Make outgoing call

-bobie

**Comment by aksthelion** [comment]
You will not find this error with quickstart code. It happens only in my app. I can forward you my source code and a video to show what happens. Let me know if you have any public email which I can forward to?

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

Were you able to follow the quickstart or find the difference between your implementation? We are still not able to reproduce the error with the latest sample code. If you believe there is a bug in the sample code or your application, please provide code snippet.

Thanks,
-bobie

**Comment by aksthelion** [comment]
I found the solution, I was doing something wrong.

**Comment by bchen-twilio** [comment]
@aksthelion 

Glad to hear that it's working now!

-bobie

**Comment by RyanLeake** [comment]
@aksthelion Mind sharing your solution? I currently appear to be having the same issue, thanks.

**Comment by AdrianDrg** [comment]
@aksthelion I'm having the same issue , can you please share your solution? Thank you!

**Comment by tragicmj** [comment]
Anyone found the solution to this?? @aksthelion @RyanLeake  @AdrianDrg ??
