### ISSUE TITLE
Client not updated with latest push token on Twilio backend

### ISSUE THREAD

**Issue by Alex-Mason-RocketInsights** [twilio/voice-quickstart-swift#214]
### Description

I was running into an issue where I was receiving an error in the Twilio debugger of `Invalid APNs device token`, however my Voice app was functioning properly after following all of the steps as described in the quickstart guide exactly. What was even stranger was the errors would only be triggered when calling from `Bob` -> `Alice` not `Alice` -> `Bob`. 

I was banging my head against the wall trying to figure out the issue. I had all my certs in order and couldn't figure out what was happening. I then tried to use two new client accounts and everything worked perfectly. I think Twilio was somehow caching/not updating a client that I made with a development account/certification when I used a production environment. That's why the error was only triggering for that one client/identity.

### Steps to Reproduce

1. Follow Quickstart guide, use development environment.
2. Create a client in your app, and register with Twilio for that client.
3. Update to production environment/certs.
4. Use the same client as before and make a phone call between two apps.
5. The app will function properly, but you will receive an error in the Twilio debugger.
6. Make two fresh clients, make a call between the two clients.
7. Receive no errors.

#### Code

The code follows the quickstart example almost exactly.

#### Expected Behavior

All former clients to be able to update to a production environment.

#### Actual Behavior

Get errors when moving clients from a development to production environment.

#### Reproduces How Often

Always, for one client of mine.

#### Logs

Invalid APNs device token

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

2.0.7 via CocoaPods

#### Xcode

10.2

#### iOS Version

11.4

#### iOS Device

iPhone X and iPad 4 for testing

**Comment by bchen-twilio** [comment]
Hi @Alex-Mason-RocketInsights 

Thanks for reporting the issue and I am sorry about the inconveniences.
The issue is due to the fact that different certificate or different `aps` environments (production/development) in the entitlement file will grant the application different device tokens, which are used as a key to register a binding in the server side. I'll check with the Twilio Notify team and see if we can have a better way of automatic binding management so that the application does not have to worry about cached push bindings and unexpected notification delivery failures. We are also working on adding a binding managing page so that SDK users have better control over obsolete bindings.

Thanks,
-bobie

**Comment by Alex-Mason-RocketInsights** [comment]
Thanks for the reply, bobie. Those sound like great solutions, thanks for the update. I'm not sure if I missed it in the README but if it's not in there it could help someone out if they know not to use development clients in a prod environment, I can image it's happened before.

**Comment by bchen-twilio** [comment]
From the application development it makes perfect sense to have production and development environments separated. I would suggest using a sub-account during the development phase and the master or a different account for the production app, that way the bindings will exist under each account and won't mess with each other. The mix of dev/prod environment hopefully only happens to the developer since very likely the same account/cert will be used, but luckily app users should not be affected unless the production cert is updated.

Hope this makes to you.
-bobie
