### ISSUE TITLE
Terminated app does not start after receiving VOIP-pushes on ios 13

### ISSUE THREAD

**Issue by azhuk89** [twilio/voice-quickstart-swift#260]
Terminated app does not start after receiving VOIP-pushes on ios 13 (the app is receiving voip-pushed as usual if it's active or in background).  On ios < 13 everything is fine.  Do you offer any solution to fix this problem now?

I found that on ios 13 voip-pushes work as expected if I add apns-expiration parameter <= 5 to his payload. Do you plan to add this parameter to voip-pushes payload?

**Steps to Reproduce**

1. Start the app
2. Kill the app
3. Make a call from the other device

**Expected Behavior**
The application starts and we start processing the voip-push.

**Actual Behavior**
The application stays terminated.

**Reproduces How Often**
100%

**Logs**
No logs, the app is terminated

**Voice iOS SDK**
3.1.1

**Xcode**
10.3 and 11.0

**iOS Version**
iOS 13

**iOS Device**
All

**Comment by bchen-twilio** [comment]
Hi @azhuk89 

I tried the CallKit quickstart (since you are using iOS 13 I am assuming CallKit is integrated) and was able to get the call while the app was terminated. Perhaps I am using the iOS 13 beta (beta4) that is several versions behind the latest. Can you share the versions of your Xcode and iOS 13 beta?

We do set the `apns-expiration` parameter when sending the notification requests to APNS but it's configured to `30` to match our signaling protocol.

Cheers,
-bobie

**Comment by azhuk89** [comment]
Hi, Bobie

I’m using xcode 11 last beta and ios 13.1 beta 2 for developers

пн, 9 сент. 2019 г. в 20:37, bobiechen-twilio <notifications@github.com>:

**Comment by bchen-twilio** [comment]
Thanks for providing the info @azhuk89. We will investigate with the latest version and keep you posted.

-bobie

**Comment by azhuk89** [comment]
Thanks, really looking forward to the news!

пн, 9 сент. 2019 г. в 21:14, bobiechen-twilio <notifications@github.com>:

**Comment by bchen-twilio** [comment]
Hi @azhuk89 

We have just released the Voice iOS SDK 5.0.0 which has some updates and API changes to comply with the new PushKit policy introduced with iOS 13 release. Please see the [changelog](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#500) and the [migration guide](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#ios-13-xcode-11-support) for more information.
Using iOS 13.1 beta4 I was able to receive the incoming call invite while the app was previously terminated. Please note that if the app fails to report PushKit pushes as CallKit incoming calls too many times, the system will dropped the push without notifying the app. (I saw the message in the MacOS Console app while testing and I had to learn this the hard way...)

Let me know if the 5.0.0 helps!

Thanks,
-bobie

**Comment by bchen-twilio** [comment]
Hi @azhuk89 

We haven't heard back from you so I am assuming the 5.0 SDK does address the original issue you were experiencing. I am closing this ticket but please feel free to reach out to us any time.

Cheers,
-bobie

**Comment by mqaiserbutt** [comment]
I'm using twilio voice 5.0 SDK but i don't get voip notification while in the background. It does work when we are inside our app though. Could you help me?

**Comment by bchen-twilio** [comment]
Hi @mqaiserbutt 

Please follow the [migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md#ios-13--xcode-11) and update your application to ensure it complies to the new PushKit policy. If you believe the problem is still happening with the updates in your environment, feel free to create a new issue with the steps, SDK logs, and Twilio Call SIDs so that we can help debug.

Thanks,
-bobie

**Comment by AleksandarTokarev** [comment]
@azhuk89  did you manage to fix this?

**Comment by suny2talk** [comment]
@bobiechen-twilio ,
I have working in react native, the same issue facing..I have used latest twilio npm, but not get the call in terminated app state in latest iOS version..

Thanks..
