### ISSUE TITLE
calDidDisconnect does not include UUID object

### ISSUE THREAD

**Issue by marecektn** [twilio/voice-quickstart-swift#27]
After finishing call there should be `callDidDisconnect(_ call: TVOCall)` delegate method called with TVOCall object having UUID children object.

This is not happening though, since there is no UUID attribute returned. Maybe its a backend bug since this SDK was working couple days ago.

I am creating new call as: `performStartCallAction(uuid: UUID(), handle: "VoIP Demo")`

Attributes of callbacking TVOCall object look like this:

![githab](https://cloud.githubusercontent.com/assets/12512106/25705409/7b5918ee-30dd-11e7-8215-6d3e951554a1.png)

Thanks!

**Comment by marecektn** [comment]
This is my start call method for callkit
```
func performStartCallAction(uuid: UUID, handle: String) {
        let callHandle = CXHandle(type: .generic, value: handle)
        let startCallAction = CXStartCallAction(call: uuid, handle: callHandle)
        let transaction = CXTransaction(action: startCallAction)
        callKitCallController.request(transaction)  { error in
            if let error = error {
                NSLog("StartCallAction transaction request failed: \(error.localizedDescription)")
                return
            }
            let callUpdate = CXCallUpdate()
            callUpdate.remoteHandle = callHandle
            ... other call Update setup
            self.callKitProvider.reportCall(with: uuid, updated: callUpdate)
        }
    }

**Comment by marecektn** [comment]
also attaching error stack:

```
libswiftFoundation.dylib`static Foundation.UUID._unconditionallyBridgeFromObjectiveC (Swift.Optional<__ObjC.NSUUID>) -> Foundation.UUID:
    0x10263c168 <+0>:  sub    sp, sp, #0x40             ; =0x40 
    0x10263c16c <+4>:  stp    x20, x19, [sp, #0x20]
    0x10263c170 <+8>:  stp    x29, x30, [sp, #0x30]
    0x10263c174 <+12>: add    x29, sp, #0x30            ; =0x30 
    0x10263c178 <+16>: mov    x20, x0
    0x10263c17c <+20>: mov    x19, x8
    0x10263c180 <+24>: cbz    x20, 0x10263c1c4          ; <+92>
    0x10263c184 <+28>: stp    xzr, xzr, [sp, #0x10]
    0x10263c188 <+32>: nop    
    0x10263c18c <+36>: ldr    x1, #0x773fc              ; "getUUIDBytes:"
    0x10263c190 <+40>: add    x2, sp, #0x10             ; =0x10 
    0x10263c194 <+44>: mov    x0, x20
    0x10263c198 <+48>: bl     0x102693ff0               ; symbol stub for: objc_msgSend
    0x10263c19c <+52>: ldr    q0, [sp, #0x10]
    0x10263c1a0 <+56>: str    q0, [sp]
    0x10263c1a4 <+60>: mov    x0, x20
    0x10263c1a8 <+64>: bl     0x102694008               ; symbol stub for: objc_release
    0x10263c1ac <+68>: ldr    q0, [sp]
    0x10263c1b0 <+72>: str    q0, [x19]
    0x10263c1b4 <+76>: ldp    x29, x30, [sp, #0x30]
    0x10263c1b8 <+80>: ldp    x20, x19, [sp, #0x20]
    0x10263c1bc <+84>: add    sp, sp, #0x40             ; =0x40 
    0x10263c1c0 <+88>: ret    
->  0x10263c1c4 <+92>: brk    #0x1

**Comment by bchen-twilio** [comment]
Hi @marecektn 

Could you share more details about the steps you are doing so we can also try to reproduce the issue you are having? I've tried the Swift CallKit quickstart myself (with beta8 SDK) but was able to get the `callDidDisconnect:` callback and `uuid` of the `TVOCall` object is valid. Steps:
- Launch the app and register for push
- Make an call from another Twilio (JS, browser) client
- Accept the incoming call from system call UI
- Hang up the call on the mobile app
- `po call.uuid` when `callDidDisconnect:` is called

Are you getting crash or you are just unable to see UUID in the `TVOCall` object?

The debug description of the `TVOCall` object you are seeing from the console was implemented before we added the CallKitIntegration category to the TVOCall class thus it's missing the `uuid` property. Sorry for the confusion and we'll add it back.

-bobie

**Comment by marecektn** [comment]
Hello @bchen-twilio
thank you for your quick reply.
I tried to go through your steps and I managed to get the UUID object with no problem.

I went through all possible combinations of calling / accepting and hanging up and my observations are (both clients are registered for push). Clients A (iOS 10.1) and B (iOS 10.3)

call init A - A hangs up: crash
call init A - B hangs up: crash
call init B - A hangs up: OK
call init B - B hangs up: OK

call inits A - B declines: crash
call inits B - A declines: callback not called (which is ok since there is no call on receiving part)

I am bit confused, it might be versions of iOS. since everytime call is inited by client B (iOS 10.3) UUID is there and valid..
anytime it is inited by client A, there is no UUID and crash occurs

Please let me know if you need further info, I can share you my backend (it is making accessTokens for devices by their name which might be the problem)

everytime I need accessToken, I am calling this endpoint:

```
@app.route('/accessToken/<clientName>')
def token(clientName):
  account_sid = os.environ.get("ACCOUNT_SID", ACCOUNT_SID)
  api_key = os.environ.get("API_KEY", API_KEY)
  api_key_secret = os.environ.get("API_KEY_SECRET", API_KEY_SECRET)
  push_credential_sid = os.environ.get("PUSH_CREDENTIAL_SID", PUSH_CREDENTIAL_SID)
  app_sid = os.environ.get("APP_SID", APP_SID)

  grant = VoiceGrant(
    push_credential_sid=push_credential_sid,
    outgoing_application_sid=app_sid
  )

  #let's register client
  token = AccessToken(account_sid, api_key, api_key_secret, clientName)
  token.add_grant(grant)

  return str(token)
```

any kind of help is much appreciated.. thanks a lot :)

**Comment by bchen-twilio** [comment]
Hi @marecektn 

Thanks for the experiments 👍 

I have a hunch but am not sure - could you help me check if the clients A (or B) is getting multiple push notifications for incoming call invite or cancellation? this could somehow mess up the UUID value of the call(-invite) object but usually this won't happen for end users in the wild since their apps will and should only be using the production Push Credential SID. However if you install the production app on the device that was used for development and the sandbox Push Credential SID was used for registration, it's possible that you get multiple push notifications for one incoming call/cancellation event.

To clarify, you are getting this crash:
- on client A device?
- when trying to call `call.uuid` in the Swift code?

Thanks
-bobie

**Comment by marecektn** [comment]
to answer your push notification question:
I am obtaining 2 push messages - 1 before call starts to ring, 1 after I accept the call (both are type of PKPushType.voIP)
But I obtain **no push message** about **canceling** the call. Is that ok?

Crash is because I am trying to call.uuid in Swift code.

I am continuing on the investigation, seems like the end of call notification is missing. Will try to run it with your quickstart app.

Thanks for help 👍

**Comment by marecektn** [comment]
next steps:
I create two instances of quickstart app that use my backend and tried all the combinations.. It worked ok. So backend bug is out of scope.

What I've notice is that you are not using iOS10 callkit for call ending.. and on my application the standard UI with Call Failed occurs everytime I hang out call (from any client)

**Comment by marecektn** [comment]
so I am using pretty much the same code as in demo of yours for hanging call up:
```
if (self.call != nil && self.call?.state == .connected) {
            self.call?.disconnect()
        }
```
but everytime I hang call there is iOS10 UI showing Call Failed.. that is suspicious

**Comment by bchen-twilio** [comment]
Hi @marecektn 

We do have CallKit example and it is included in this quickstart. You can either use Cocoapods to set up the workspace, which will include both the regular and the CallKit quickstart projects in it, or just use the CallKit xcodeproject.

When the app/SDK failed to end the call, what is the error you are seeing? is it from CallKit or is it from the SDK? one of the CallKit FAQ of the Voice SDK is that developers get `com.apple.CallKit.error.requesttransaction error 4.` error when trying to send the end-call-action to CallKit. It would be great if you could also try the CallKit Swift quickstart we provide and see if you are seeing the same error on your device and environment.

Thanks!

By the way, I should explain a bit about the push notifications - currently the Twilio Voice service will send two kinds of push notifications, `call` & `cancel`. The push notification you are getting after accepting the call is exactly the `cancel` notification and it's because currently Twilio Voice service allows same identity to be registered on multiple clients and once a call is answered/rejected or canceled, the service will send `cancel` notifications to all of the clients registered with that identity, including the client who answered the call.

About the `call.uuid` crash, it's very odd. I am wondering if this is specific to that device or iOS version. Would it be too much trouble for you to try to grab `call.uuid` using our CallKit quickstart on your device?

cheers
-bobie

**Comment by marecektn** [comment]
hi @bchen-twilio 
thanks for reply, I am experiencing crash on uuid which is not optional and therefore app crashes.

what I am trying to do now is to implement your callkit demo viewcontroller into my app (which seems to work ok).. 

therefore I assume I am doing something wrong on my abstraction layers in app.
I am closing this defect for now since your demo works and will let you know what I was missing.

thanks for help!

**Comment by bchen-twilio** [comment]
👍  Awesome @marecektn!
Absolutely happy to know your findings and hopefully other SDK users can potentially benefit from it.

Cheers
-bobie

**Comment by marecektn** [comment]
@bchen-twilio ok, time to show the cards.. after couple of debugging hours I found out I was missing most important line of them all &ndash; setting call uuid in make in `CXStartCallAction`

since I had to put both iOS9 and iOS10 support in one framework, I created `CallManager` that creates its own interface for iOS version respectively. By moving all logic from view controller into couple of abstraction layers, I forgot to make assignment of `call?.uuid = uuid` in makeCall method.

I was wrongly assuming that UUID created in call `performStartCallAction(uuid: UUID(), handle: "VoIP Demo")` will be handled with the `call` instance itself.

But I was assigning uuid correctly in `acceptCall` method which brings light into my former debug observations when half of the cases were success.

Thank you very much for your support, I appreciate it very much. 👏

**Comment by bchen-twilio** [comment]
Thanks for sharing your findings with us @marecektn and please feel free to let us know if you have any suggestion or you run into any problem in the future.
Looking forward to seeing your awesome voice app!

cheers
-bobie

**Comment by RnyG** [comment]
Hey guys, i have a question, which handle could i use in the example says let handle = "Voice Bot", but this would be used then? @bchen-twilio @marecektn

**Comment by bchen-twilio** [comment]
Hi @RnyG 

Sorry I don't think I am following your question.
Are you trying to make an outgoing call to a specific name (handle) or are you trying to report the name to the system for displaying the incoming call?
