### ISSUE TITLE
Updating access token while application is not running

### ISSUE THREAD

**Issue by shshalom** [twilio/voice-quickstart-swift#36]
Hi,
I need help understanding how do I get a notification about token expiration while the application is not running (killed). I am struggling with this issue where the application was killed and during that state the token was expired. Now if another user tries to call, he will get "Call ended" since the target user has no valid token.

Is there anyway to get a notification for a token update, maybe in a similar way as TwilioAccessManager works, only also while the application is killed?

**Comment by bchen-twilio** [comment]
Hi @shshalom

This is a good question.
Actually the mobile will still be able to receive incoming call push notifications as long as the registration is still valid. The application in this case will launch automatically upon receiving the VoIP push, and it should be able to accept the call using a special beidge token embedded in the notification payload.

Unless the applications explicitly call the unregister method or the VoIP token itself has expired, the registered binding of the identity should continue to receive pushes.

-bobie

**Comment by shshalom** [comment]
Hey @bchen-twilio, so just to validate what you're saying,  if my application was killed, and wasn't reopened during  the access token lifetime, an Incoming call would still be able to wake up the application, allowing the call to occur?

Another question if I may, is this also true for Android?

-shalom

**Comment by bchen-twilio** [comment]
Hi @shshalom 

- The concept of the access token, for the Programmable Voice mobile clients, is for operation authentication, e.g. (un)registering or making a call. The token needs and only has to be inside valid TTL at the time making the method calls.
- It's slightly different but similar for incoming calls, just that this time the SDK will be using a special bridge-token embedded in the notification payload sent by the Twilio Voice service in order to accept and connect the call. No access token involved this time.
- Apple's PushKit framework makes sure the app is woken up if it was killed, in this case, upon receiving the VoIP push notification and guarantees the application enough time to start everything even if the it is still in the background.

I am afraid I am not expert of Android but I will definitely reach out to them and let you know the expected behaviors.

cheers
-bobie

**Comment by shshalom** [comment]
Thanks @bchen-twilio, that helped a lot 👍

**Comment by bchen-twilio** [comment]
@shshalom any time!
Please feel free to reopen or file a new ticket in case you run into any issue in the future.
Looking forward to seeing your awesome Voice apps!
