### ISSUE TITLE
Incoming call when application state is inactive

### ISSUE THREAD

**Issue by remelephant** [twilio/voice-quickstart-swift#41]
In our company we are trying to integrate Twilio Programable voice SDK into our application. I'm trying to find out, is there any way to get the incoming call after user killed the application? (everything is working when application is in background state)

**Comment by bchen-twilio** [comment]
Hi @remelephant 

One of the benefits of using Apple's VoIP Service is that it guarantees higher priority and it even launches the application for you if it was not active or backgrounded.

We've do have validation steps to try killing the app and launching it using the incoming call push notifications.

Could you share more details with us? are you experiencing trouble receiving push notifications or just want to confirm that the SDK works fine in this case?

Thanks
-bobie

**Comment by remelephant** [comment]
Hi @bchen-twilio, thank you for your response!
This is my callInviteReceived method in bottom, when I am calling to device after killing the application this method is not activating and the app is doing nothing, when I'm calling to device second time the notification is appearing and everything is working.

func callInviteReceived(_ callInvite: TVOCallInvite) {
        if server.outgoingCallIsActive == true {
            return
        }
        self.present(self.incomingCallVC!, animated: false, completion: nil)
        
        if (UIApplication.shared.applicationState != UIApplicationState.active) {
            let notification = UILocalNotification()
            notification.alertBody = "Incoming call from \(callInvite.from), while inactive)"
            notification.soundName = UILocalNotificationDefaultSoundName
            UIApplication.shared.presentLocalNotificationNow(notification)
        }
    }

**Comment by bchen-twilio** [comment]
Hi @remelephant 

Could you check if the PushKit does receive the VoIP push after the app is killed?
If indeed the push notification is received but the `TwilioVoice.handleNotification:delegate:` method is not called, then something is wrong with the SDK's notification handler.
It could either be that the payload is corrupted (very unlikely) or there is some error when the SDK is parsing the push payload.

Could you also provide us a few things?
- SDK verbose level log
- just curious, since iOS 8 kind of behaves slightly differently with PushKit, but what is the iOS version of the device you are using?

I've just tried with our testbed app with the killing the app steps, with or without CallKit, and I was able to see the app reacting upon receiving the incoming call push notifications, either showing the push notification banner or the system incoming (CallKit) call.

Let me know.
-bobie

**Comment by remelephant** [comment]
bchen-twilio, thank you for your response!

I have solved the problem by removing 
`self.present(self.incomingCallVewController, animated: false, completion: nil)`
line from 
`func callInviteReceived(_ callInvite: TVOCallInvite) {}` method. I am using iOS9, iOS10 and iOS11 beta (without CallKit), the problem occurred only when application is killed. Thank you one more time for your quick responses!

**Comment by bchen-twilio** [comment]
Nice!
Thanks for sharing the valuable findings with us. Just to make sure I understand:
- are you able to get the incoming call VoIP push even if the app is killed?
- if yes, are you getting the `callInviteReceived:` callback from the SDK on receiving the push?

Feel free to reach out to us any time.

**Comment by remelephant** [comment]
Yes, I'm getting both VoIP push and callInviteReceived: callback from the SDK.
Thank you!
