### ISSUE TITLE
Detect if call is busy

### ISSUE THREAD

**Issue by remelephant** [twilio/voice-quickstart-swift#43]
I would like to know if there is built in solution in Twilio SDK to detect if the call receiver is on other call (i.e. call is busy).

**Comment by bchen-twilio** [comment]
Hi @remelephant

Good question.
Twilio currently don't really tell the caller whether the receiver is already in a call due to the nature that we support same client identity being registered on multiple devices/places. We leave the power to the application to reject/ignore/disconnect the call on the receiver side, but eventually the caller will always get the same result (SIP `BYE`) from the signaling protocol standpoint and the SDK always notifies the application via the call-did-disconnect callback.

-bobie
