### ISSUE TITLE
iOS Energy Crash with TwilioSDK 6

### ISSUE THREAD

**Issue by benford-servicem8** [twilio/voice-quickstart-swift#481]
Hi, 

We have an iOS app running the TwilioSDK and are receiving 10's of Energy based crashes daily which appear to be caused by the TwilioSDK using too much CPU during calls while the app is in the background. 

Eg. 
-High CPU Usage Termination (9 seconds cpu time over 9 seconds (100% cpu average), exceeding limit of 60% cpu over 15 seconds)
-High CPU Usage Termination (90 seconds cpu time over 90 seconds (100% cpu average), exceeding limit of 50% cpu over 180 seconds)
-High CPU Usage Termination (90 seconds cpu time over 158 seconds (57% cpu average), exceeding limit of 50% cpu over 180 seconds)

The backtraces vary, but all appear to belong to the SipStack during a call.
![image](https://user-images.githubusercontent.com/25942406/136143160-f82bee80-bf2c-44b8-aa8e-3f707be928c8.png)

Is there anything we can do to reduce the amount of CPU being consumed during calls so the iOS watchdog doesn't terminate our process?

Thanks
Ben

**Comment by bobiechen-twilio** [comment]
@benford-servicem8 Thanks for reporting this. We will perform some instrumentation and gather some debugging data then get back to you.
Just to confirm - is it as simple as putting the app to the background during a call and does this happen only when the app is not in the foreground, i.e. does this also happen when the device is lock?

**Comment by benford-servicem8** [comment]
@bobiechen-twilio Thanks, we haven't been able to reproduce the crash, it seems energy based crashes are disabled when the debugger is attached. When we profile the app while debugging the CPU doesn't exceed 5% during a call, however we have logging that confirms that the CPU on some calls is much higher. 

We estimate that about 1% of calls are experiencing the issue. The most common report we are receiving from customers is that the call will drop 10 seconds after answering, which matches the "exceeding limit of 60% cpu over 15 seconds" rule. The iOS energy watchdog only applies when the app is in the background, and i would assume lock screen as well.

**Comment by bobiechen-twilio** [comment]
Hi @benford-servicem8 

Just want to let you know that we haven't forgotten about this one and are actively investigating with different profiling tools. Hope to update you soon.

**Comment by bobiechen-twilio** [comment]
I've CPU-profiled our internal test app but didn't see the jump of CPU usage when moving the app to the background mid call under different network connection types (Wifi/cellular), since the screenshot from the description seems to indicate the signaling stack was causing the high CPU. I did see a couple of WebRTC audio related threads working pretty hard but they managed to keep at ~50% of CPU load.

I also checked the env data from the user feedback but it doesn't seem to be caused by older models of devices since they are using a very recent model (iPhone 12). Is there any chance we can gather more information regarding device models or network environment of the crashes

<img width="2035" alt="Screen Shot 2021-10-20 at 4 14 53 PM" src="https://user-images.githubusercontent.com/16326574/138185961-95afa8e2-c6c6-41bf-aa75-ba168e68c2e7.png">
?
