### ISSUE TITLE
Open source plans?

### ISSUE THREAD

**Issue by julien-c** [twilio/voice-quickstart-swift#53]
Hello,

I'm an existing Twilio user (for server side services until now) considering whether to use this SDK for my next product.
I see in the app logs that you're bundling PJSIP as a SIP library. Is there a lot more going on, or is it mostly a package around a SIP client?

Are there any plans to open source part of this library?

Thanks 🙏

**Comment by bchen-twilio** [comment]
Hey @julien-c 

In addition to bundling the PJSIP library as our signaling engine, we do have some patches upon the PJSIP library in order to make communication between mobile clients and Twilio Voice service smoother.

The Programmable Voice mobile SDKs (currently in beta) leverages the Twilio Notify service, in conjunction with the Twilio Voice service, to provide more reliable incoming capability via device push notifications provided by Apple/GCM/FCM.
With the existing server-side helper libs or REST APIs of Twilio I am sure you are already making awesome apps that can connect mobile devices via PSTN calling capability. Why not also VoIP client using the also-awesome Programmable Voice SDKs? :p

cheers
-bobie

**Comment by ceaglest** [comment]
Hi @julien-c,

Unfortunately we don't have any plans to open source our mobile Voice SDKs at this time. I hope that between Bobie's response and mine you have the information that you need, even if it wasn't the answer that you wanted.

If anything changes we will let you know.

Thanks,
Chris Eagleston

**Comment by julien-c** [comment]
Thanks!
