### ISSUE TITLE
Incoming call doesn't connect properly

### ISSUE THREAD

**Issue by talalt** [twilio/voice-quickstart-swift#68]
### Description

Hello, Twilio team. I use CallKit in my app. When I make a call to my app, the call arrives properly, but when I answer that call( CallKit's **provider:performAnswerCallAction**), the call doesn't connect(**TVOCallDelegate's callDidConnect** method doesn't get called). And after nearly 30 seconds the call disconnect because of TimeOut error. It happens not always, nearly 40-50%
### Steps to Reproduce

1. Alice calls Bob
2. Bob tap Answer button
3. Call's status still connecting

#### Reproduces How Often

40-50%

#### Logs
When doesn't connect:  [twilio-income-call-no-connect-log.txt](https://github.com/twilio/voice-quickstart-swift/files/1340566/twilio-income-call-no-connect-log.txt)

When connects properly:  [twilio-income-call-connect-log.txt](https://github.com/twilio/voice-quickstart-swift/files/1340567/twilio-income-call-connect-log.txt)

#### Voice iOS SDK

[e.g. 2.0.0-beta16 via CocoaPods]

#### Xcode

[e.g. 8.3.1]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6]

**Comment by bchen-twilio** [comment]
Hi @talalt 

I am sorry that you are experiencing failure connecting the call. The time out (408) error in the log indicates the Twilio server could not produce a response within a suitable amount of time. In this case, the `call:didFailWithError:` callback method should be called so that the application can handle the UI transition for the best call experience.

-bobie

**Comment by talalt** [comment]
Hi @bchen-twilio 

But I want to know, why my call doesn't connect? I use CallKit, so I run 
`guard let call = self.callInvite?.accept(with: incomingCallController!) else {
            action.fail()
            return
        }`

inside of **provider(_ provider: CXProvider, perform action: CXAnswerCallAction)** function.

**Comment by bchen-twilio** [comment]
Hi @talalt 

Assuming no error or time-out happening, the SDK should be able to connect the incoming call and notify the application delegate via the `callDidConnect:` callback method, otherwise the `call:didFailWithError:` callback should be raised to make sure the application receives the state termination.

Could you help us check if you are getting correct `TVOCallDelegate` callbacks?
Thanks.

bobie

**Comment by talalt** [comment]
Hi @bchen-twilio 

Yes, I get TVOCallDelegate callbacks, and when I try to accept callInvite, if there time-out happens, delegate `call:didFailWithError:` callback raised. Thanks.

**Comment by bchen-twilio** [comment]
Hi @talalt 

If you are seeing the timeout error too frequently, please collect the Call-SIDs (`TVOCall.sid`) from the Xcode debugger or from the [Programmable Voice Dashboard](https://www.twilio.com/console/voice/dashboard) and reach out to us, then we can try to diagnose why the network connectivity is causing the timeout.'

Thanks,
bobie

**Comment by bchen-twilio** [comment]
Closing this ticket for now. Please feel free to open a new issue.
Thanks.
