### ISSUE TITLE
How to get called number?

### ISSUE THREAD

**Issue by talalt** [twilio/voice-quickstart-swift#70]
### Description
Hello, dear Twilio team. In my app an user can buy many virtual numbers. So,  I have a question about how to identify in which number come incoming call . I try to get it from `callInviteReceived(_:)` method using `callInvite.to`, but that gives something like **7_596da5d29fdf2** but not my number. Thanks!

**Comment by bchen-twilio** [comment]
Hi @talalt 

This is a good question but first let me make sure that I understand what you are trying achieve.
Are you trying to display the `from` number on the UI of the mobile client that is receiving the call-invite? or are you trying to display the `callInvite.to` same on the receiver side?

As for what is being shown in the `to` or `from` field, we will probably need you to provide the TwiML response and perhaps the server app implementation so that we have more clue why you are seeing the value like `7_596da5d29fdf2`.

Thanks.
bobie

**Comment by talalt** [comment]
Hi @bchen-twilio 

> are you trying to display the callInvite.to same on the receiver side
I'm trying to display the **callInvite.to** on the receiver side

**Comment by bchen-twilio** [comment]
Hi @talalt 

If the call receiver is a mobile client, then it's has to be registered with an identity which may or may not be the same as a regular PSTN phone number. This identity will then decide to where the Twilio Voice/Notify service sends the push notification and will be the value as you see in the `TVOCallInvite.to`.

**Comment by bchen-twilio** [comment]
Closing the issue for now. Please feel free to open a new issue.
Thanks.
